Update medInria-macOS.yml

diff --git a/.github/workflows/medInria-macOS.yml b/.github/workflows/medInria-macOS.yml
--- a/.github/workflows/medInria-macOS.yml
+++ b/.github/workflows/medInria-macOS.yml
@@ -28,12 +28,18 @@ jobs:
 
     - name: Install dependencies
       run: |
-        # brew info cmake
         brew install qt@5
         QT5_PREFIX=$(brew --prefix qt@5)
-        ls -l $QT5_PREFIX
-        export QT5_DIR="$QT5_PREFIX/lib/cmake/Qt5"
-        echo "QT5_DIR is set to $QT5_DIR"
+        QT5_CONFIG_PATH=$(find "$QT5_PREFIX" -name "Qt5Config.cmake" | head -n 1)
+        if [ -n "$QT5_CONFIG_PATH" ]; then
+          QT5_DIR=$(dirname "$QT5_CONFIG_PATH")
+          export QT5_DIR
+          echo "QT5_DIR is set to $QT5_DIR"
+        else
+          echo "Error: Qt5Config.cmake not found. Check your Qt5 installation."
+          exit 1
+        fi
+        # brew info cmake
         # brew info swig
         # brew info git-lfs
 
