[GithubAction] compilation on Apple chips of macOS workflow

diff --git a/.github/workflows/medinria-macos.yml b/.github/workflows/medinria-macos.yml
--- a/.github/workflows/medinria-macos.yml
+++ b/.github/workflows/medinria-macos.yml
@@ -34,8 +34,8 @@ on:
 
 env:
   BUILD_TYPE: Release
-  #QT5_DIR: "/opt/homebrew/opt/qt@5/lib/cmake/Qt5" # Apple chip
-  QT5_DIR: "/usr/local/opt/qt@5/lib/cmake/Qt5" # Intel chip
+  QT5_DIR: "/opt/homebrew/opt/qt@5/lib/cmake/Qt5" # Apple chip
+  #QT5_DIR: "/usr/local/opt/qt@5/lib/cmake/Qt5" # Intel chip
   # Secrets added on https://github.com/medInria/medInria-public/settings/secrets/actions/new and on your fork for testing purpose
   BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
   P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
@@ -44,7 +44,7 @@ env:
 jobs:
   build:
     # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
-    runs-on: macos-26-intel #macos-latest (Apple chip)
+    runs-on: macos-latest
 
     steps:
     - name: Checkout repository
@@ -52,39 +52,57 @@ jobs:
       with:
           ref: ${{ inputs.BRANCH }}
 
+    - name: Save in environment variable in case of automatic runs
+      run: |
+        echo "RELEASE=${{ inputs.RELEASE || 'V6.0.0' }}" >> $GITHUB_ENV
+
     # Dependencies, already on the runner: pipx, cmake
-    # TODO swig?
     - name: Install dependencies
       run: |
         brew install qt@5
-        #echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Apple chip
-        echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Intel chip
+        echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Apple chip
+        #echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Intel chip
         brew link --force qt@5
-        sudo ln -s /usr/local/Cellar/qt@5/5.15.18/mkspecs /usr/local/mkspecs
-        sudo ln -s /usr/local/Cellar/qt@5/5.15.18/plugins /usr/local/plugins
         brew install boost
-        #brew install swig
         brew install libomp
         echo "OpenMP_ROOT=$(brew --prefix libomp)" >> $GITHUB_ENV
-
-        # to get an older version of CMake
-        brew uninstall --ignore-dependencies cmake
-        pipx install cmake==3.31.10
+        pipx install dmgbuild
+        pipx ensurepath
 
     - name: Test dependencies
       run: |
         pipx --version
+        which dmgbuild
         cmake --version
         ls $QT5_DIR
 
     ### Steps for macOS signing with self-signed certificate ###
     #
-    # 1. Create a p12 certificate on a physical macOS.
-    # 2. On the mac, copy the p12 certificate with: 'base64 -i MDS-certificate.p12 | pbcopy'.
-    # 3. On https://github.com/medInria/medInria-public/settings/secrets/actions/new
-    #   - add BUILD_CERTIFICATE_BASE64 with the previously encoded lines,
-    #   - add P12_PASSWORD with p12 password.
-    # 4. For test purposes you need to add the secrets also on your fork.
+    # 1. Create a p12 certificate on a physical macOS:
+    #    - Open /Applications/Utilities/Keychain Access.app or in /System/Library/CoreServices/Applications on newer macOS.
+    #    - Menu Keychain Access -> Certificate Assistant -> Create a Certificate...
+    #         - Name: MDS-certificate.
+    #         - Identity Type: Self‑Signed Root.
+    #         - Certificate Type: Code Signing.
+    #    - Switch the certificate to "Always Trust":
+    #         - Select the certificate in "login" and "Certificates".
+    #         - Double-click on it.
+    #         - In "Trust" section, choose "Always Trust" for "When using this certificate".
+    #         - Close the window and validate with admin password.
+    #         - If needed: restart computer.
+    # 2. Export the certificate as p12:
+    #    - In Keychain Access find the certificate line.
+    #    - Left click to display the private key.
+    #    - Right click on the private key -> Exporter "MDS-certificate".
+    #    - Choose a name (MDS-certificate) and the format (Personal Information Exchange .p12).
+    #    - Define a strong password and save MDS-certificate.p12.
+    #    - If necessary, keep them in a safe place.
+    # 3. Import certificate in CI/CD:
+    #    - On the physical macOS, copy the p12 certificate with: 'base64 -i MDS-certificate.p12 | pbcopy'.
+    #    - On https://github.com/medInria/medInria-public/settings/secrets/actions/new.
+    #        - add BUILD_CERTIFICATE_BASE64 with the previously encoded lines.
+    #        - add P12_PASSWORD with p12 password.
+    #    - For test purposes you need to add the secrets also on your forks.
     ###
 
     # https://github.com/marketplace/actions/import-code-signing-certificates
@@ -100,29 +118,26 @@ jobs:
       run: |
         # Extract the PEM certificate from the p12
         echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > /tmp/cert.p12
-        openssl pkcs12 -legacy -in /tmp/cert.p12 -passin pass:"$P12_PASSWORD" -clcerts -nokeys -out /tmp/cert.pem
+        openssl pkcs12 -legacy -in /tmp/cert.p12 -passin pass:"$P12_PASSWORD" \
+          -clcerts -nokeys -out /tmp/cert.pem
+
+        # Display a failure when the certificate is about to expire
+        openssl x509 -in /tmp/cert.pem -checkend 604800 -noout || {
+          echo "ERROR: certificate '$CERT_NAME' expires in less than 7 days"
+          echo "Current expiry date: $(openssl x509 -in /tmp/cert.pem -enddate -noout | cut -d= -f2)"
+          exit 1
+        }
 
         # Add trusted certificate to system keychain
         sudo security add-trusted-cert -d -r trustRoot -p codeSign \
           -k /Library/Keychains/System.keychain /tmp/cert.pem
 
-    - name: Add keychain from import-codesign-certs step to search list
-      shell: bash
-      run: |
-        security list-keychains -d user -s \
-          "$HOME/Library/Keychains/signing_temp.keychain-db" \
-          "$HOME/Library/Keychains/login.keychain-db" \
-          /Library/Keychains/System.keychain
-
     - name: Verify certificate
       shell: bash
       run: |
-        # List every identities
-        security find-identity -v -p codesigning
-
-        # Search for our certificate
         security find-identity -v -p codesigning | grep -F -q "$CERT_NAME" || {
           echo "Error, certificate '$CERT_NAME' not found in valid identities"
+          security find-identity -v -p codesigning
           exit 1
         }
 
@@ -158,5 +173,5 @@ jobs:
       with:
         file: ${{github.workspace}}/build/${{env.BINARY_NAME}}
         asset_name: ${{env.BINARY_NAME}}
-        tag: ${{ inputs.RELEASE }}
+        tag: ${{env.RELEASE}}
         overwrite: true
